import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { cookieToInitialState } from 'wagmi'
import { headers } from 'next/headers'

import { getConfig } from '@/wagmi_helper'
import { Providers } from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'ZK ABE Client',
    description: 'Generated by Fu-Chuan Chung',
}

export default function RootLayout(props: { children: React.ReactNode }) {
    const initialState = cookieToInitialState(
        getConfig(),
        headers().get('cookie'),
    )

    return (
        <html lang="en">
            <body className={inter.className}>
                <Providers initialState={initialState}>
                    {props.children}
                </Providers>
            </body>
        </html>
    )
}
